module.exports = {
  apps: [
    {
      name: 'trademetrix-api',
      script: 'uvicorn',
      args: 'main:app --host 0.0.0.0 --port 8000 --workers 2',
      cwd: '../apps/api',
      interpreter: 'python3.12',
      env: {
        PYTHONPATH: '.',
      },
      env_file: '../.env',
      watch: false,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '../../logs/api-error.log',
      out_file: '../../logs/api-out.log',
      merge_logs: true,
    },
    {
      name: 'trademetrix-web',
      script: 'node',
      args: 'node_modules/.bin/next start',
      cwd: '../apps/web',
      env: {
        PORT: 3000,
      },
      env_file: '../.env',
      watch: false,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '../../logs/web-error.log',
      out_file: '../../logs/web-out.log',
      merge_logs: true,
    },
    {
      name: 'trademetrix-cron',
      script: 'python3.12',
      args: '-c "from market.symbol_master import symbol_master; import asyncio; asyncio.run(symbol_master.sync_nse_bhavcopy())"',
      cwd: '../apps/api',
      cron_restart: '0 2 * * *',
      autorestart: false,
      env_file: '../.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
}
